from typing import Tuple
from numpy.typing import NDArray

class QuantumState:
    def __init__(self, qubits_number: int) -> None: ...
    def apply1(self, pos: int, gate: NDArray) -> None: ...
    def apply2(self, pos1: int, pos2: int, gate: NDArray) -> None: ...
    def dens1(self, pos: int) -> NDArray: ...
    def dens2(self, pos1: int, pos2: int) -> NDArray: ...
    def measure(self, pos: int, uniform_sample: NDArray) -> int: ...
    def reset(self, pos: int, uniform_sample: NDArray) -> None: ...
    def total_reset(self) -> None: ...
    def dens_large(self, qubit_positions: Tuple[int, ...]) -> NDArray: ...
    @property
    def state_array(self) -> NDArray: ...
    @property
    def qubits_number(self) -> int: ...

def array2state(array: NDArray) -> QuantumState: ...
